Source/Libraries/GSF.Communication/UdpClient.cs
Source/Libraries/GSF.Communication/UdpServer.cs

Fixed bug described in: https://openpdc.codeplex.com/discussions/644288

Fixed socket descriptor error with mono when using UDP

---

Source/Libraries/GSF.TimeSeries/Data/MySQL/InitialDataSet.sql
Source/Libraries/GSF.TimeSeries/Data/Oracle/InitialDataSet.sql
Source/Libraries/GSF.TimeSeries/Data/PostgreSQL/InitialDataSet.sql
Source/Libraries/GSF.TimeSeries/Data/SQL Server/InitialDataSet.sql
Source/Libraries/GSF.TimeSeries/Data/SQLite/InitialDataSet.sql

For issue #5, added SDG&E to the COMPANY table in the GSF initial data SQL scripts.

Added SDG&E to company list in GSF schema

---

Source/Documentation/FilterExpressions.md

I'm not sure if this is the right location for this information, but we have spent some time working with it so I thought other people might find it useful.

Add documentation for Filter Expressions.

---

Source/Libraries/Hadoop/src/TVA/Hadoop/MapReduce/Datamining/SAX/SlidingTSClassifier_kNN.java
Source/Libraries/Hadoop/src/TVA/Hadoop/MapReduce/Datamining/SAX/UCI_CSV_1NN_Classifier.java

refactor code in UCI_CSV_1NN_Classifier class to use up-to-date Hadoop and jmotif APIs

Gsf hadoop update

---

Source/Libraries/Hadoop/src/GSF/Hadoop/MapReduce/Datamining/SAX/UCI_CSV_1NN_Classifier.java

The original code doesn't have a comment to explain what it is for. This update gives a simple explanation.

add comments and purpose of the class

---

Source/Libraries/GSF.Web/Model/ModelController.cs

Simplified Authentication checks and removed unnecessary try-catch

Cleaned up auth checks and try-catch

---

Source/Libraries/GSF.SELEventParser/CommaSeparatedEventReport.cs

Apply sqrt(2) multiplier to current measurements from CEV files

---

Source/Libraries/GSF.Core.Shared/GSF.Core.Shared.projitems
Source/Libraries/GSF.Core.Shared/NumericalAnalysis/AnalogFilter.cs
Source/Libraries/GSF.Core.Shared/NumericalAnalysis/DigitalFilter.cs
Source/Libraries/GSF.Core.Shared/NumericalAnalysis/FFT.cs
Source/Libraries/GSF.Core.Shared/NumericalAnalysis/FilterState.cs

Added Filters and FFT from Gemstone/SciSync into GSF.Core

Numeric analytics

---

Source/Libraries/GSF.Core.Shared/NumericalAnalysis/AnalogFilter.cs
Source/Libraries/GSF.Core.Shared/NumericalAnalysis/DigitalFilter.cs

Added a few Filter functions that got lost

Filter fixes

---

Source/Libraries/GSF.SELEventParser/CommaSeparatedEventReport.cs

GSF.SELEventParser: Parse fault voltage and current measurements from CEV file header

---

Source/Libraries/GSF.Web/Model/ModelController.cs

This is needed to add additional Logic in Sec urityGroup Controller to pull Display Name from AD/Azure

Allow override for Query functions

---

Source/Libraries/GSF.InstallerActions/CustomActions.cs

Updated to prevent logging recursion

Installer action updates

---

Source/Libraries/GSF.Web/Security/AuthenticationHandler.cs

Prevents basic auth red herring.

GSF.Web: Improved exception message context for Azure errors

---

Build/Scripts/MasterBuild.buildproj

Precursor to automatically submitting pull requests via build scripts.

Introduce PushToVersionBranch parameter into MasterBuild.buildproj

---

Source/Libraries/GSF.Web/Model/ModelController.cs

This Adds 2 pagination Endpoints to the Model Controller. 
I did not bother adding one if no Filters are present (equivalent of `Get()`) since we can always supply an empty `Searches` It does mean there is only `POST` support when doing Pageination but I figure that would be fine.

Added Pageination

---

Build/Scripts/GridSolutionsFramework.buildproj

Adding `GitRepo` as a property to property group to fix nightly build issue.

Added GitRepo as a property to fix NightlyBuilds

---

Source/Applications/Wave Demo Apps/UpdateWAVMetaData/Program.cs
Source/Libraries/GSF.Communication/GSF.Communication.csproj
Source/Libraries/GSF.Windows/GSF.Windows.csproj

Minor updates

---

Source/Libraries/Adapters/CsvAdapters/CsvExportAdapter.cs

Added FramesPerSecond property to CsvExportAdapter to allow for timestamp normalization when downsampling is enabled.
This corrects issue identified in ticket #1518

Added timestamp normalization feature to CsvExportAdapter 

---

Source/Libraries/Adapters/CsvAdapters/CsvExportAdapter.cs

When using normalized sub-second downsampling in the CsvExportAdapter, only export measurements that fall on the downsampling interval.
This corrects issue identified in ticket #1518

Added feature to only export on downsampling interval for CsvExportAdapter

---

Source/Libraries/Adapters/CsvAdapters/CsvExportAdapter.cs

* This frame-counting strategy works for both subsecond intervals and long intervals so I just went all in and got rid of the special casing for `DownsampleInterval < 1.0D`.
* I changed the terminology from "normalized" to "aligned" because I felt it was easier to understand.
* Although it would probably be due to a configuration error, I limited `m_downsampleFrameCount` to be at least 1 to prevent divide-by-zero errors.
* I tweaked the condition that checks downsample interval against the timestamp difference because it's unnecessary when performing alignment and would only invite potential issues due to rounding errors.

Fixes for downsampling in CsvExportAdapter

---

Source/Libraries/GSF.Web/Security/Views/Groups.cshtml

GSF.Web: Fixes table header labels to show "Group" instead of "User"

---

Source/Libraries/Adapters/PhasorProtocolAdapters/PhasorMeasurementMapper.cs
Source/Libraries/Adapters/PhasorWebUI/PhasorConfigController.cs
Source/Libraries/GSF.PhasorProtocols/Anonymous/ConfigurationFrame.cs

Improved config compare operations when using deserialized configuration file.

Config out of sync updates 2

---

Source/Libraries/Adapters/PhasorProtocolAdapters/PhasorMeasurementMapper.cs

Loading cached configuration out of sync marker on thread pool to ensure call to ConfigurationOutOfSync proceeds quickly for statistic operations on a large system.

PhasorProtocolAdapters: ConfigurationOutOfSync optimization

---

Source/Libraries/GSF.PhasorProtocols/IEC61850_90_5/DataFrame.cs
Source/Libraries/GSF.PhasorProtocols/IEEEC37_118/DataFrame.cs
Source/Libraries/GSF.PhasorProtocols/IEEEC37_118/PhasorValue.cs
Source/Libraries/GSF.PhasorProtocols/UI/DataModels/RealTimeStream.cs
Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/RealTimeMeasurementUserControl.xaml
Source/Libraries/GSF.PhasorProtocols/UI/WPF/ViewModels/RealTimeStatistics.cs
Source/Libraries/GSF.PhasorProtocols/UI/WPF/ViewModels/RealTimeStreams.cs

Improved phasor UI feedback for out of sync display on Output Measurements screen

Config out of sync UI optimizations

---

Source/Libraries/Adapters/PhasorWebUI/Device Viability Calculations.TagTemplate

Should we update Full Calculations.TagTemplate to match?

GSF-2 Fix angle diff calculations (off by 180)

---

Source/Libraries/GSF.PhasorProtocols/UI/DataModels/RealTimeStream.cs
Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/RealTimeMeasurementUserControl.xaml
Source/Libraries/GSF.TimeSeries/UI/Converters/ObjectToVisibilityConverter.cs

This update places the UI feedback at the proper level in the hierarchy for PDCs

Improved UI feedback on out of sync operations for PDCs

---

Source/Libraries/GSF.Security/AdoSecurityProvider.cs
Source/Libraries/GSF.Security/AzureADSettings.cs
Source/Libraries/GSF.Security/SecurityProviderCache.cs

These updates correct issues found when authenticating with external (i.e., Guest) users.

Azure AD fixes for external users

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/GrafanaFunctionBase.cs

Improved error message when unsupported group operation is selected.

GrafanaAdapters minor update

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/ExcludeRange.cs
Source/Libraries/Adapters/GrafanaAdapters/GrafanaDataSourceBase_ApiControllerOperations.cs
Source/Libraries/Adapters/GrafanaAdapters/TimeSliceScannerAsync.cs
Source/Libraries/GSF.Core.Shared/TypeExtensions.cs

ExcludeRange implemented `and` logic when it should have been coded with `or` logic

GrafanaAdapters: Fixed value test logic for ExcludeRange function

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Evaluate.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Switch.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/Common.cs
Source/Libraries/Adapters/GrafanaAdapters/GrafanaAdapters.csproj

Added Switch Function.
It takes a slice and uses the first number as an index to select a value from all other values in the slice.

Added grafana Switch

---

Source/Libraries/Adapters/GrafanaAdapters/DataSources/DataSourceValueGroup.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Evaluate.cs
Source/Libraries/Adapters/GrafanaAdapters/GrafanaDataSourceBase.cs

Improved `Evaluate` Grafana function to only return results with a good time value

Eval time ops

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Clamp.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Reference.cs
Source/Libraries/Adapters/GrafanaAdapters/GrafanaAdapters.csproj

Adds Ref Function and Clamp Function

Ref function

---

Source/GridSolutionsFramework.sln.DotSettings
Source/Libraries/Adapters/PhasorProtocolAdapters/CommonPhasorServices.cs
Source/Libraries/GSF.TimeSeries/ServiceHostBase.cs

* Improved `Invoke` service host base operation to allow for default values and provided better exception messages.
* Improved format of `ListCommands` service host base operation and added default parameter value listing.
* Added default options for `GetFilteredStatusMessages` adapter command.

Improved adapter command Invoke defaults

---

Source/Libraries/GSF.TimeSeries/ServiceHostBase.cs

This allows adapter status details to be pulled from service controller API

Updated "list" command to have an optional actionable response

---

Source/Libraries/GSF.PhasorProtocols/UI/WPF/ViewModels/RealTimeStatistics.cs

Updated statistic monitoring operation for device outputs screen

GSF.PhasorProtocols.UI.WPF: Improved statistic monitoring

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/KalmanFilter.cs
Source/Libraries/Adapters/GrafanaAdapters/GrafanaAdapters.csproj
Source/Libraries/GSF.Core/GSF.Core.csproj
Source/Libraries/GSF.Core/NumericalAnalysis/KalmanFilter.cs

Adds a Kalman (or linear quadratic estimation (LQE)) filter as an available function to GSF and as an available Grafana function.
https://en.wikipedia.org/wiki/Kalman_filter

Kalman filter

---

Source/Libraries/GSF.Web/Hosting/WebPageController.cs

Adds an option to `IWebPageControllerBuilder` to redirect all responses that would return 404 Not Found to the Default Web Page instead.
This is done by registering a branching middleware before the `WebPageController` middleware on the main branch of the Owin pipeline. The branching middleware invokes the `WebPageController` middleware on the main branch, and if the response from the main branch is 404 Not Found, then it subsequently invokes a second `WebPageController` on a separate branch of the pipeline. The second `WebPageController` uses the same `WebServer` instance as the first, but has a slightly modified route template to force all resources to resolve to the default web page.
Since the second `WebPageController` is only invoked when the first responds with 404 Not Found, this …

GSF.Web: Add an option for web applications to redirect all 404 Not Found to a single page

---

Source/Libraries/Adapters/DynamicCalculator/EmailNotifier.cs

This adds a Connectionstring parameter to prevent an email from going out on every recalculation as long as the condition is met.
If `MultiTriggerPrevention` is `true` an email will only go out the first time the condition evaluates to `true` subsequent evaluation will be ignored until the condition evaluates to `false` at least once.
This prevents the system from sending out continous emails when using complex alarm logic

Added Logic to prevent excessive triggering if condition is met

---

Source/Libraries/Adapters/PIAdapters/PIOutputAdapter.cs
Source/Libraries/Adapters/PhasorProtocolAdapters/CommonPhasorServices.cs
Source/Libraries/Adapters/PhasorProtocolAdapters/MemoryCache.cs
Source/Libraries/Adapters/PhasorWebUI/Views/AddSynchrophasorDevice.cshtml
Source/Libraries/GSF.Core.Shared/Units/EE/VoltageLevel.cs
Source/Libraries/GSF.PhasorProtocols/UI/WPF/ViewModels/InputWizardDevices.cs

Applied consistent common voltage levels across all libraries.

Common voltage level application

---

Source/Libraries/Adapters/PIAdapters/PIOutputAdapter.cs

Added diagnostic functions to PI output adapter.

PIOutputAdapter: Added tag / value diagnostic operations

---

Source/Libraries/Adapters/PIAdapters/PIOutputAdapter.cs

Fixed bit state mapping assignments and display.

PIOutputAdapter: Fixed bit state mappings

---

Source/Libraries/Adapters/PhasorWebUI/PhasorWebUI.csproj
Source/Libraries/Adapters/PhasorWebUI/Views/AddSynchrophasorDevice.cshtml
Source/Libraries/Adapters/PhasorWebUI/Views/BulkTagTemplate.cshtml
Source/Libraries/Adapters/PhasorWebUI/Views/SelectGroupDevices.cshtml
Source/Libraries/GSF.Web/Shared/Views/GraphMeasurements.cshtml

Synchronizes minor automation updates from device wizard screen in `openHistorian` to `GSF` for reuse.
Other related pre-existing views in `openHistorian` were also moved here.

Sync device wizard view

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Reference.cs

Added support for Refernce Function when using Type MeasurmentValue (assume all signals are Phases)

Added MeasurementValue support to Reference

---

Source/Libraries/Adapters/DynamicCalculator/DynamicCalculator.cs

Alarms only produce measurements when the alarm state changes so the published value will quickly expire become unusable for computations. In that case, we want to be able to use the latest value of the alarm regardless of how old it is.
I also removed superfluous logic in `ProcessMeasurements()`. This logic could never actually update `m_latestTimestamp` because it was already updated in `PublishFrame()`. Perhaps it was a leftover from an iteration that attempted to use `QueueMeasurementsForProcessing()` instead of `PublishFrame()`.

DynamicCalculator: Add option for PublishWithBadState to support alarm inputs

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Reference.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/ParameterParsing.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/Parameters.cs
Source/Libraries/Adapters/GrafanaAdapters/GrafanaDataSourceBase.cs
Source/Libraries/Adapters/GrafanaAdapters/GrafanaDataSourceBase_AncillaryOperations.cs
Source/Libraries/Adapters/GrafanaAdapters/Model/Common/DataSourceValueGroup.cs

This PR exposes outgoing metadata maps to functions to allow for adjustments and augmentations. 
Also, PR updates `Reference` function to optionally adjust midpoint of reference angle, i.e., first angle in expression.
Testing recommended before production deployment.

Grafana function metadata augmentation

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/AddMetadata.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Exceeds.cs

Fixes inheritance for the new Grafana Functions

Fixed inheritance for Compute Classes

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Exceeds.cs

This is causing issues if there are any NaNs in the data. So we ignore any NaN in the beginning and treat NaN in the middle as continuing the previous value. NaN at the end are also treated as continuing previous value

Fixed NaN operation in threshold exceed check

---

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/ExceedsAt.cs
Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/FilterOutliers.cs

Fixed logic error with last point in `exeeds` operation

GrafanaAdapters: Exceeds at fix

---

Source/GridSolutionsFramework.sln.DotSettings
Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/HomeUserControl.xaml.cs

UI lead/lag times adjusted so that time differentials exceed those of calculations and adapters.

GFS.PhasotProtocols.UI.WPF: Applied a 1.5 second additional offset to UI

---

Source/GridSolutionsFramework.sln.DotSettings
Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/HomeUserControl.xaml.cs
Source/Libraries/GSF.TimeSeries/Transport/UI/WPF/UserControls/HomeUserControl.xaml
Source/Libraries/GSF.TimeSeries/Transport/UI/WPF/UserControls/HomeUserControl.xaml.cs

Synchronized latest UI updates to `GSF.TimeSeries.Transport.UI.WPF.HomeUserControl` for SIEGate

Home control UI updates

---

Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/HomeUserControl.xaml.cs
Source/Libraries/GSF.TimeSeries/Transport/UI/WPF/UserControls/HomeUserControl.xaml.cs

Minor update to add config setting encrypt attribute with manual update

Added encrypted attribute to manual settings update

---

Source/Libraries/GSF.Core/Data/Model/ITableOperations.cs
Source/Libraries/GSF.Core/Data/Model/TableOperations.cs

```c#
/// <summary>
/// Gets flag that determines if the specified field exists.
/// </summary>
/// <param name="fieldName">Field name to check.</param>
/// <returns><c>true</c> if field is found; otherwise, <c>false</c>.</returns>
public bool FieldExists(string fieldName)
{
return s_propertyNames.TryGetValue(fieldName, out _);
}
```

Added FieldExists method to TableOperations

---

Source/GridSolutionsFramework.sln.DotSettings
Source/Libraries/GSF.Core/Data/DataSetEqualityComparer.cs
Source/Libraries/GSF.Core/Data/Model/ExtensionAttributeBase.cs
Source/Libraries/GSF.Core/Data/Model/ITableOperations.cs
Source/Libraries/GSF.Core/Data/Model/SortExtensionAttribute.cs
Source/Libraries/GSF.Core/Data/Model/TableOperations.cs
Source/Libraries/GSF.Core/TypeExtensions.cs

Currently, code must opt-in to enable.
Related PRs:
https://github.com/GridProtectionAlliance/openHistorian/pull/113
https://github.com/GridProtectionAlliance/openPDC/pull/175

Adds configurable secure order by validation to table operations

---

Source/Libraries/Adapters/DynamicCalculator/DynamicCalculator.cs

This PR implements adapter commands to view the actual values of measurements received by the adapter as well as the values of variables used in the calculation of a given result. This is intended to assist with troubleshooting adapter configuration when the result of the calculation doesn't match expectations.
---
Here is a recommended approach for enabling these messages in a remote console application.
```
q
filter -include message MYCALC
r
invoke MYCALC RaiseVerboseMessages
```
Once the console has captured some of the output, you can disable the messages again with these commands.
```
q
invoke MYCALC StopVerboseMessages
```
---
Here is some example output from an adapter using the following calculation:
`If(freq >= 45 and freq <= 55 and volt >= 10000, 1, 0)`
FYI, the `x` variable is …

DynamicCalculator: Adapter command to assist troubleshooting

---

Source/Libraries/GSF.Core.Shared/Units/EE/VoltageLevelExtensions.cs

Adds `34` as a valid common voltage level

Update to common voltage levels

---

Source/Libraries/Adapters/DynamicCalculator/DynamicCalculator.cs

Syntax now allows a directly specified list of measurements

Improved options for array variable declaration in DynamicCalculator
