Source/Libraries/Hadoop/src/TVA/Hadoop/MapReduce/Historian/File/ArchiveFileAllocationTable.java
When I was running the original code, I found only a portion of the files in the input path on HDFS are read by the Mapper. I debugged the code while searching the solutions online. It turns out to be the issue of an outdated API FSDataInputStream.read, which has been replaced by FSDataInputStream.readFully (see the link ([https://stackoverflow.com/questions/25897627/datainputstream-read-vs-datainputstream-readfully])
I replaced outdated API with a newer one. The problem was successfully solved.
=> replace outdated API to avoid reading less from the stream

Source/Libraries/Hadoop/src/TVA/Hadoop/MapReduce/Historian/HistorianRecordReader.java
Replaced the old hadoop packages (org.apache.hadoop.mapred.*) with the new ones (org.apache.hadoop.mapreduce.*)
Replaced the implementation of the old RecordReader interface (Hadoop v1.x API) with the new one (Hadoop v2.x API). Some of the methods do not exist anymore
=> replace the old implmentation of RecordReader interface with new ones

Source/Libraries/Hadoop/src/TVA/Hadoop/MapReduce/Historian/HistorianInputFormat.java, Source/Libraries/Hadoop/src/TVA/Hadoop/MapReduce/Historian/HistorianRecordReader.java
Replaced all the old packages (org.apache.hadoop.mapred.*) with the new ones (org.apache.hadoop.mapreduce.*);
Replaced the old API getRecordReader with new API createRecordReader defined in class org.apache.hadoop.mapreduce.InputFormat<K,V>
=> use new packages; use API createRecordReader instead of getRecordReader

Source/Libraries/GSF.Communication/Transport.cs
We are using an oscillation detection program that uses the GSF library to connect to an openPDC instance. When running remotely, I found the IPStack was always being set to IPv6. I ran a debugger and found that when "interface" is not specified in the config string, IPStack.Default is returned. This eventually defaults to the first IPStack of the local machine.
I made this change so that the IPStack is based on the server address rather than the client when the interface value is not provided. In my case, my local machine is configured for IPv6 and IPv4 while the server only supports IPv4. This caused the connection to fail.
By checking the address type of the server in the connection string, the communication library handles this edge case while keeping the same behavior if the …
=> GSF.Communication: Updated GetInterfaceIPStack to better select IPStack

Source/Libraries/GSF.Web/Security/AuthenticationHandler.cs, Source/Libraries/GSF.Web/Security/AuthenticationOptions.cs, Source/Libraries/GSF.Web/Security/Scripts/Login.js, Source/Libraries/GSF.Web/Security/Views/Login.cshtml, Source/Libraries/GSF.Web/Shared/Scripts/gsf.web.client.js
Adds a `/Security/logout` endpoint to applications using [AuthenticationHandler](https://github.com/GridProtectionAlliance/gsf/blob/master/Source/Libraries/GSF.Web/Security/AuthenticationHandler.cs). Logging out of such applications is as easy as navigating to the endpoint.
This PR also updates `Login.cshtml` to make use of this endpoint automatically, eliminating the need to call [SecurityHub.Logout()](https://github.com/GridProtectionAlliance/gsf/blob/a2f461ae55805b9bde5f50bb0dd75f49b3540574/Source/Libraries/GSF.Web/Security/SecurityHub.cs#L112) in every application. Instead, applications can simply navigate to `/@GSF/Web/Security/Views/Login.cshtml?logout` to get a user-friendly logout page.
=> Add logout endpoint for applications using AuthenticationHandler

Source/Libraries/GSF.Core/GSF.Core.csproj, Source/Libraries/GSF.Core/IO/FileProcessor.cs, Source/Libraries/GSF.Core/Threading/ManagedCancellationTokenSource.cs
The `m_requeueTokenSource` variable in FileProcessor was being disposed prematurely due to a logic error in the async processing loop. This was causing errors in the file processors for MiMD and openXDA. However, fixing the logic error introduces a race condition so the logic needed to be redone. This resulted in the creation of the `ManagedCancellationTokenSource` class.
=> Fix logic to dispose requeue token source in FileProcessor

Source/Libraries/GSF.TimeSeries/Data/Oracle/GSFSchema.sql
I synced the Oracle database script up with the SQL Server database script.
* The `CREATE VIEW` statements are such a mess in both scripts that I skipped right over them.
* The triggers and foreign keys in the Oracle database script were not reviewed thoroughly. I only checked to make sure the SQL Server foreign keys were also defined in the Oracle database script.
**Oracle** Extra fields in Company table was removed
https://github.com/GridProtectionAlliance/gsf/blob/4c62a38af42df7e40bf235bd5f399acf8d0911b4/Source/Libraries/GSF.TimeSeries/Data/Oracle/GSFSchema.sql#L106-L107
**Oracle** Extra field in the AccessLog table was removed
https://github.com/GridProtectionAlliance/gsf/blob/4c62a38af42df7e40bf235bd5f399acf8d0911b4/Source/Libraries/GSF.TimeSeries/Data/Oracle/GSFSchema.sql#L944
**SQL …
=> Oracle database script cleanup

Source/Libraries/GSF.Core/IO/FileProcessor.cs
In openXDA, a massive flood of `Watcher_Changed` events caused a massive backlog of actions to build up on the watcher thread, which then caused a massive flood of `ObjectDisposedException`s to be thrown when working through that backlog after the `FileProcessor` was disposed. Forcefully clearing the thread's queue of actions should help prevent that, and doing so after detaching from events in `ClearTrackedDirectories()` should prevent more actions from queuing up in the meantime.
=> GSF.Core: Clear watcher thread when FileProcessor is disposed to help prevent ObjectDisposedExceptions

Source/Libraries/GSF.InstallerActions/CustomActions.cs
Without the trailing slash, the reservation doesn't get removed.
```
C:\WINDOWS\system32>netsh http add urlacl http://+:8989/ user=GPA\Testing
URL reservation successfully added
C:\WINDOWS\system32>netsh http delete urlacl http://+:8989
URL reservation delete failed, Error: 87
The parameter is incorrect.
C:\WINDOWS\system32>netsh http delete urlacl http://+:8989/
URL reservation successfully deleted
```
=> GSF.InstallerActions: Fix command used to remove HTTP namespace reservations

Source/Libraries/GSF.Core.Shared/StringExtensions.cs
After discussing with Stephen this seemed like the best course of action if a value is `NULL`.
Currently it throws a `NullReferenceException` which causes problems.
We did discuss using an empty string in this case, but that may cause issues if something is trying to parse it into something else later on. In theory a `NULL` setting should now default to the default value of the setting (same as if it was not specified at all)
=> Skip NULL values in JoinKeyValuePairs

Source/Libraries/GSF.Security/AdoSecurityProvider.cs
This will allow us to use these properties in the `ImpersonationSecurity` Provider in XDA.
=> Enabled inheritance for Error Messages

Source/Libraries/Adapters/TestingAdapters/NormalizeSubsecondTimestampsFilterAdapter.cs, Source/Libraries/Adapters/TestingAdapters/TestingAdapters.csproj
Creates a new filter adapter that allows subsecond timestamps to be normalized for a specified frame rate.
=> TestingAdapters: Added NormalizeSubsecondTimestampsFilterAdapter

Source/Libraries/GSF.Communication/GSF.Communication.csproj, Source/Libraries/GSF.Windows/GSF.Windows.csproj
This fixes GSF.Communictation and GSF.Windows `.csproj` files - newer VS versions are picky about this component subtype parameter.
=> Fixed component subtypes for projects

Source/Libraries/GSF.TimeSeries/Data/MySQL/GSFSchema.sql, Source/Libraries/GSF.TimeSeries/Data/Oracle/GSFSchema.sql, Source/Libraries/GSF.TimeSeries/Data/PostgreSQL/GSFSchema.sql, Source/Libraries/GSF.TimeSeries/Data/SQL Server/GSFSchema.sql, Source/Libraries/GSF.TimeSeries/Data/SQLite/GSFSchema.sql, Source/Tools/AdapterExplorer/AdapterExplorer.csproj
When `FramesPerSecond` is zero, the `HistorianMetadata` view can/will fail. 
This PR makes sure view does not fail for each SQL database represented.
=> GSF.TimeSeries: Fixed HistorianMetadata SQL views

Source/Libraries/Adapters/PhasorProtocolAdapters/CommonPhasorServices.cs, Source/Libraries/GSF.TimeSeries/Statistics/StatisticsEngine.cs
Added a secondary check to prevent duplicated statistics from being created and updated statistics validation step in `CommonPhasorServices` to check for and remove duplicate statistics.
=> Stat dups fix

Source/Libraries/GSF.ServiceProcess/ServiceHelper.cs
Caught this bug while investigating a separate issue in MiMD.
=> GSF.ServiceProcess: Pass client ID into ServiceHelper status update queue

Source/Libraries/GSF.Web/Model/ModelController.cs
This fixes a bug where we modified the `SearchText` properties of a Filter when building the where clause.
=> Fixed SQL Exception when using Pageination and Filters

Source/Libraries/GSF.Security/AdoSecurityProvider.cs, Source/Libraries/GSF.Web/Security/SecurityHub.cs
Changed ADOSecurity Provider to use email field to match users instead of ID. That way we don't have to add `#Ext#` anywhere
=> Fixed Azure query to match email instead of ID

Source/Libraries/GSF.Web/Model/ModelController.cs
I realized the whole point of the `SQLSearchModifier` is to generate complex conditions that won't work inside a `SQLSearch`object with SQL injection avoidance.
=> Updated SQLSearchModifier to return string

Source/Applications/TsfManager/App.xaml.cs, Source/Libraries/GSF.PhasorProtocols/UI/DataModels/Device.cs
The first commit applies the system's current culture settings to the WPF UI. Without this, it will default to en-US, which explains why numbers were displaying with periods instead of commas when using `en-AT` culture.
The second commit relaxes the regex validation for lat/long so that a number like `-98,6` will not fail validation. The regex was being applied to a string created using the current culture settings regardless of what was being used for the display. This explains why the validation was failing despite the UI showing a number with a valid format.
The first commit will need to be applied to every Manager application individually, not just TSFManager.
=> GSF-4 TSFManager localization fixes

Source/Libraries/GSF.Web/Model/ModelController.cs
This fixes an issue with the PagedList endpoint throwing an exception in `CountSearchResults` method because of `param` being a List instead of an array.
=> Fix bug in PagedList endpoint

Source/Libraries/Adapters/PhasorWebUI/Views/AddSynchrophasorDevice.cshtml
In cases where phase labels may be designated with Red/Yellow/Blue, i.e., `R`/`Y`/`B`, instead of `A`/`B`/`C` - updated current phase label matching strategy to also ignore `R`, `Y` and `B` phase designations for finding matched individual phase currents that should be used for 3-phase `MW`/`MVAR`/`MVA` calculations.
=> Updated 3-phase MW/MVAR/MVA calcs to include R, Y, B phase designations

Source/Libraries/GSF.Core.Shared/IO/FilePath.cs
See https://github.com/gemstone/common/pull/9
=> GSF.Core: Avoid converting empty path to absolute path in AddPathSuffix()

Source/Libraries/GSF.Web/Model/ModelController.cs
Added Public BindingFlag to the `ModelController` constructor so that we are able to find the method under the `SQLSearchModifier` attribute. Without this SQLSearchModifier property will stay null, since GetMethods will be unable to find the method.
=> Added Public binding flag to GetMethods for SQLSearchModifer property

Source/Libraries/GSF.COMTRADE/Schema.cs
Fixes an issue reported in https://github.com/gemstone/comtrade/issues/3. Need to follow up with a PR for Gemstone as well.
=> GSF.COMTRADE: Fix parsing for fields starting with TimeFactor

Source/Libraries/GSF.COMTRADE/AnalogChannel.cs, Source/Libraries/GSF.COMTRADE/DigitalChannel.cs, Source/Libraries/GSF.COMTRADE/Parser.cs, Source/Libraries/GSF.COMTRADE/SampleRate.cs, Source/Libraries/GSF.COMTRADE/Schema.cs, Source/Libraries/GSF.COMTRADE/TimeOffset.cs, Source/Libraries/GSF.COMTRADE/Timestamp.cs, Source/Libraries/GSF.COMTRADE/Writer.cs
Fix culture issues reported in https://github.com/gemstone/comtrade/issues/2
=> GSF.COMTRADE: Use invariant culture for all numeric conversions

Source/Libraries/GSF.TimeSeries/ServiceHostBase.cs
When the application tries to write to a windows event log source that does not affect it currently fails to start without any error.
The installer usually creates the datasource so this is only an issue when running debug on a system that has never had the installer run.
This commit just prevents an exception in the EventLog writing from failing out the entire startup/initialization routine. Note that the GSF logger may not be up at that point so writing there is not an option until later.
=> Fix issue when EventLog Source does not exist

Source/GridSolutionsFramework.sln.DotSettings, Source/Libraries/Adapters/Dnp3Adapters/Dnp3Adapters.csproj, Source/Libraries/Adapters/Dnp3Adapters/Dnp3InputAdapter.cs, Source/Libraries/Adapters/Dnp3Adapters/IsExternalInit.cs, Source/Libraries/Adapters/Dnp3Adapters/MasterConfiguration.cs, Source/Libraries/Adapters/Dnp3Adapters/MeasurementLookup.cs, Source/Libraries/Adapters/Dnp3Adapters/MeasurementMap.cs, Source/Libraries/Adapters/Dnp3Adapters/TimeSeriesSOEHandler.cs, Source/Tools/DNP3ConfigGenerator/Program.cs
1) Added optional DNP3 quality to `MeasurementStateFlags` mappings (works for STTP) - see `MapQualityToStateFlags` property.
2) Added option to publish DNP3 quality flags as separate output measurements (works for IEEE C37.118 or STTP) - see `PublishFlagsAsSeparateMeasurements` property.
Like value measurements, quality measurements are expected to be pre-defined outside the adapter, i.e., the adapter does not currently auto-create tags. There is an external Python script that exists for this purpose. 
The `PublishFlagsAsSeparateMeasurements` property is used to determine if the adapter should include DNP3 quality flags as part of the measurement outputs. The `TagMatchPattern` and `QualityTagSuffix` properties are used to determine the tag name for the quality flags. 
Generally, the value …
=> Dnp3Adapters Updates

Source/GridSolutionsFramework.sln.DotSettings, Source/Libraries/Adapters/HistorianAdapters/LocalOutputAdapter.cs, Source/Libraries/GSF.Historian/Files/MetadataFile.cs, Source/Libraries/GSF.Historian/Files/MetadataRecord.cs
File will auto-regenerate when checksum failure is detected.
This fixes issue with status files growing excessively large due to corruption in metadata file data reading impossibly large ID numbers.
Upgrade from old version just fails integrity check since it doesn't exist and re-generates metadata file:
```
[STAT] Attempting connection to stat [C:\Program Files\openHistorian\Statistics\]...
[STAT] WARNING: Detected corrupted metadata file, attempting regeneration...
[STAT] Connection attempt failed for stat [C:\Program Files\openHistorian\Statistics\]: MetadataFile data integrity check failed.
[STAT] Disconnected from stat [C:\Program Files\openHistorian\Statistics\].
[STAT] Attempting connection to stat [C:\Program Files\openHistorian\Statistics\]...
[STAT] MetadataService has been …
```
=> Added checksum to OH 1.0 metadata file

Source/Libraries/Adapters/GrafanaAdapters/Functions/QueryParameters.cs, Source/Libraries/Adapters/GrafanaAdapters/GrafanaDataSourceBase.cs, Source/Libraries/Adapters/GrafanaAdapters/GrafanaDataSourceBase_AncillaryOperations.cs
The square distribution supports laying out overlapping points in a grid pattern. It places points in an order that builds out from the center so that no matter how many points there are in an overlapping group of points, the formation still appears to be centered around the original location of the points.
You can also do a simple horizontal or vertical distribution by specifying only one of the two offset values.
**Example Grafana query:**
`FILTER ActiveMeasurements WHERE SignalType = 'FREQ'; squareDistribution={xOffset=15; yOffset=15; zoom=8}`
=> GrafanaAdapters: Implement square distribution to differentiate overlapping points on a map

Source/Tools/DataMigrationUtility/DataMigrationUtilityScreen.Designer.cs, Source/Tools/DataMigrationUtility/DataMigrationUtilityScreen.cs
The other day, Ritchie and I spent some hours trying to think of clever ways to get useful error messages out of the `DataMigrationUtility` on a customer's system while it was spamming tangentially related foreign key errors. I'm hoping this update would make it a whole lot easier to get the information we need for troubleshooting.
=> [DataMigrationUtility] Usability updates

Source/Libraries/GSF.Core/Data/AdoDataConnection.cs, Source/Libraries/GSF.Core/Data/DataExtensions.cs, Source/Libraries/GSF.Core/Data/Model/TableOperations.cs
Note that function of `AddNewOrUpdateRecord` is still dependent on detection of default primary keys values.
If a model use intends to insert a record with default values for primary keys, user will need to manually differentiate between "add" and "update" operation in code and not use `AddNewOrUpdateRecord` function in this scenario.
=> Update to return loaded record even when primary keys are default values

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/Median.cs, Source/Libraries/GSF.Core/Collections/CollectionExtensions.cs
The name of the `Median()` function is misleading, which led to some sneaky logic errors in the islanding detection algorithm. Splitting the implementation like this should help to resolve potential confusion. I also snuck in some optimizations for non-array lists and collections which are not lists.
=> GSF.Core: Split implementation of Middle() vs Median()

Source/Libraries/GSF.COMTRADE/Timestamp.cs
See https://github.com/gemstone/comtrade/pull/8
=> GSF.COMTRADE: Use invariant culture for double-to-string conversion when parsing timestamps

Source/Libraries/Adapters/GrafanaAdapters/GrafanaDataSourceBase_AncillaryOperations.cs, Source/Libraries/GSF.PhasorProtocols/UI/DataModels/OutputStream.cs, Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/HomeUserControl.xaml, Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/HomeUserControl.xaml.cs, Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/InputStatusMonitorUserControl.xaml.cs
This PR adds "_current_" lead/lag time as well as configurable "_suggestion_" to lead/lag time adjustment pop-up on TSF home screens to reduce confusion on current value during updates.
Screen also now adds a checkbox that can optionally prefer most recent device time, e.g., GPS-timestamped PMU time, instead of depending on time-reasonability checks against local clock, e.g., when PMU time can be trusted more than local clock. This handles scenarios such as server having wide, floating clock time when server is domain-attached, and end user not having any other clock control options.
=> Time deviation threshold improvements with use remote time option

Source/Libraries/GSF.TimeSeries/Adapters/IndependentActionAdapterManagerBase.cs
Automatically propagates `PerformTimestampReasonabilityCheck` and `UseLocalClockAsRealTime` properties in bulk adapters to child adapters.
=> Updated IndependentActionAdapterManagerBase property propogation

Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/ExceedsAt.cs, Source/Libraries/Adapters/GrafanaAdapters/Functions/BuiltIn/FilterOutliers.cs
1) Adds optional `fallsBelow` parameter that determines if the value should be considered inversely as falling below the threshold instead of exceeding.
2) Adds optional `reportEndMarker` parameter that determines if a value should be reported at the point when threshold stops being exceeding. Parameter is helpful for the Grafana state timeline panel, allowing span of threshold exceeded to be visualized (see images below). 
New signature:
```
Exceeds(threshold, [fallsBelow = false], [returnDurations = false], [reportEndMarker = false], expression)
```
Improved edge case handling:
=> ExceedsAt function improvements

Source/Libraries/GSF.TimeSeries/Adapters/IndependentActionAdapterManagerBase.cs
The queue of input measurement keys was unnecessary, because the synchronized operation was copying the reference to a local variable anyway. However, by keeping an old collection of input measurement keys in the queue, the adapter is much more likely to use an old collection of inputs against an updated `DataSource` leading to mismatches.
---
If you specify inputs manually by signal ID, `InputMeasurementKeys` might end up with a measurement key for an inactive measurement. This results in an error:
> Failed to initialize adapter OSCILLATIONTEST!44291B81-4467-4A33-BD1A-6C19473BFD99: Cannot use NONE as input to frequency based oscillation detector. One voltage angle input measurement is required. Cannot initialize adapter.
By filtering inactive measurements early, we avoid these types of …
=> GSF-12 IndependentActionAdapterManagerBase fixes

Source/Libraries/Adapters/PowerCalculations/PhasorAddition.cs, Source/Libraries/Adapters/PowerCalculations/PowerCalculations.csproj
Adds an adapter that calculates the sum or difference of 2 Phasors as a Phasor.
It's based on the Sequence Calculator (single instance). I am not too worried about minor improvements since hopefully this will be replaced with Gemstone soon.
=> Added Phasor Addition Adapter

Source/Libraries/GSF.Web/Security/AuthenticationHandler.cs, Source/Libraries/GSF.Web/Security/AuthenticationMiddleware.cs, Source/Libraries/GSF.Web/Security/AuthenticationOptions.cs
`AuthenticationHandler` does not depend on any of the underlying logic in the `Microsoft.Owin.Security` base classes. Removing them helps to simplify the code a bit in `AuthenticationHandler`. Furthermore, although we have not determined the root cause of the major performance issues we are seeing on client systems, testing suggests we can very likely avoid it by removing these base classes from the Owin pipeline.
Changes basically consist of implementing a handful of properties that were provided by the base classes, some minor cleanups in `AuthenticationHandler` methods, and implementing the `AuthenticationMiddleware.Invoke()` method. Nothing changes about how the middleware is used, so there should be no breaking changes downstream.
=> GSF-13 Do not use Microsoft.Owin.Security base classes for AuthenticationMiddleware

Source/Tools/APPPDCImporter/APPPDCImporter.csproj, Source/Tools/SELPDCImporter/SELPDCImporter.csproj
Whenever I open the project in Visual Studio, it adds these `SubType` fields automatically to these two csproj files.
=> Add csproj fields from VS

Source/Libraries/GSF.PhasorProtocols/UI/WPF/ViewModels/PhasorMeasurements.cs
ReloadConfig call updated to run even when no historian is defined for measurement.
This allows changes to auto-propagate over STTP on manual update.
=> Updated metadata measurement save to always call reloadconfig

Source/Libraries/GSF.Web/Security/AuthenticationHandler.cs
The anonymous principal is used at the end of the authentication process if no `SecurityProvider` is found to assign to `Request.User`. But in the case of anonymous resources, the `AuthenticationHandler` allows the user passed in by IIS to leak into the pipeline. Then, in `AuthorizeAsync()`, the `UserHasLogoutRole()` function calls `WindowsPrincipal.IsInRole()` using a `WindowsPrincipal` representing a nonexistent Windows user on a group called `logout` that likely doesn't exist. If we replace the `WindowsPrincipal` with the anonymous principal, this should no longer happen.
Tested using SE Browser, and this change didn't cause any problems.
=> GSF.Core: Use anonymous principal when accessing anonymous resources

Source/Libraries/GSF.Web/Security/AuthenticationHandler.cs
Resolves an issue with the anti-CSRF token validator.
When generating a form token, the token validator uses `IIdentity.IsAuthenticated` to determine whether to encode a username in the token. Due to the changes in #363, the `Login.cshtml` page was encoding the username "anonymous" in its form token. When validating the form token for the `AuthTest` page, the validator was expecting an empty username.
`GenericIdentity` is authenticated so long as it has a name. Therefore, it is impossible to use `GenericIdentity` to get an identity with the name `anonymous` that is not authenticated. `ClaimsIdentity` is authenticated so long as it has an authentication type so we can simply pass a name claim with no authentication type into the constructor.
=> Ensure the anonymous principal is not authenticated

Source/GridSolutionsFramework.sln.DotSettings, Source/Libraries/Adapters/DynamicCalculator/DatabaseNotifier.cs
This PR makes the `DatabaseNotifier` adapter much more useful by supporting variable names and values in the templated database command parameters, in addition to `{Acronym}` and `{Timestamp}` which were already available.
For example:
- `VariableList={x = A:FREQ; y = B:MAG; z = C:ANG}`
- `DatabaseCommand=INSERT INTO RemoteSystemTable(Freq, Mag, Ang) VALUES(@p0, @p1, @p2)`
- `DatabaseCommandParameters={{x}, {y}, {z}}`
- `ExpressionText=x > 60.04`
Also includes improved feedback reporting.
=> Added variables to database command template parameters

Source/Libraries/Adapters/DynamicCalculator/DynamicCalculator.cs
Client reported an issue with the following connection string expression:
```
VariableList={x = DMD_DIFESA!TRIGGER; y = DMD_DIFESA!WARNING;}
```
The trailing semi-colon caused an empty variable to be created.
=> Updated the VariableList expression to ignore empty values

Source/GridSolutionsFramework.sln.DotSettings, Source/Libraries/Adapters/GrafanaAdapters/Annotations/AnnotationExtensions.cs, Source/Libraries/Adapters/HistorianAdapters/LocalOutputAdapter.cs, Source/Libraries/Adapters/PhasorProtocolAdapters/CommonPhasorServices.cs, Source/Libraries/GSF.Historian/Files/ArchiveReader.cs
Updated STAT archive validations to not force update to CacheWrite setting to allow Grafana queries quick data access.
=> Do not force stat cache writes

Source/Libraries/GSF.TimeSeries/ImmediateMeasurements.cs, Source/Libraries/GSF.TimeSeries/TemporalMeasurement.cs
It's unintuitive when `ImmediateMeasurements` has a `RealTimeFunction` property, but doesn't use it when validating timestamps during measurement updates. Since `ImmediateMeasurements` is the only user of the `TemporalMeasurement` class, we can just change the signature of `TemporalMeasurement.SetValue()` to receive the value returned by `ImmediateMeasurements.RealTimeFunction()` and use it for validation.
=> GSF.TimeSeries: Don't use UTC when validating timestamps during temporal measurement updates

Source/Libraries/GSF.Core/Console/Arguments.cs
Let's break it down.
1. `(?<Open>")` matches the opening quote. The named capturing group is used later in two other capturing groups.
2. `(?:[^\\"]*(?:\\.)*)*` first attempts to match as many characters as it can, so long as they're not a backslash or a quote. If it's a backslash, it will forcefully match the character after the backslash and continue to look for backslashes. The asterisk on the outside allows us to go back and match not-backslash-or-quote characters again as many times as we need to until we find a quote.
3. `(?<Close-Open>")` matches the closing quote. The capturing group syntax causes the regex engine to delete the `Open` capturing group and capture everything in between the quotes as the `Close` capturing group.
4. `(?(Open)(?!))` conditionally fails to match `(?!)` …
=> GSF.Core: Fix performance of regex used to parse console args

Source/Libraries/GSF.PhasorProtocols/UI/DataModels/RealTimeStream.cs, Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/InputStatusMonitorUserControl.xaml, Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/RealTimeMeasurementUserControl.xaml, Source/Libraries/GSF.PhasorProtocols/UI/WPF/UserControls/RealTimeStatisticUserControl.xaml
The first commit introduces `GroupJoin()` and `GroupBy()` in the Linq queries when loading `RealTimeStream` models from the database. This reduces nested loops over the device and measurement tables, improving performance when first navigating to the page.
The second commit enables UI virtualization on `TreeView` instances, which vastly improves performance when expanding a node with a lot of children. With virtualization enabled, the WPF renderer will limit the number of rendering objects it allocates based on what's currently visible in the scroll view. See: https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-improve-the-performance-of-a-treeview
The last commit limits these pages to show only enabled measurements, which just seems like a good UX feature for testing. A …
=> Optimize monitoring screens in Manager applications
